### ISSUE TITLE
DynamoDbClient.get_by_query - maxitems

### ISSUE THREAD

**Issue by ngr** [bimpression/sosw#43]
1) The current implementation of counter doesn't return full count for Large results. It returns only the first page of paginated response. Should paginate and sum that.

2) Should introduce the MaxItems attribute for get_by_query. Name i accordingly with AWS convention. Make sure it works well with different `Select` attributes (both fields and count).

**Comment by ngr** [comment]
This will require an integration test with 5000+ write operations.

**Comment by markbulgakov** [comment]
Nick: Sophie please check if it's true. And close if needed

**Comment by nimirium** [comment]
OK I checked. I tried it with 5000 items in the DB and max_items=1723.
max_items works fine, unless we request the count of items. And I fixed it in this PR: https://github.com/bimpression/sosw/pull/118

**Comment by ngr** [comment]
just prohibit get_count and max_items arguments at the same time.
